# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3063d3eb740a8587d49366296a0b7c1490f73a3e10e354a44998abf47f7a0800982b486a8b20cdbe06a5211f534010e7fac43df894bd62c55d2bdf1be2597729

test:
  secret_key_base: 73f86b312b671ffa38ab79da6c1ad384e8fc9849aa9b4db9cfd716903bcff7ed9d2bcb03f8846441c60b60742ad52c56a6db084ed82cd63905607c4602bfc76b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
